<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Project Sn'=>'项目编号',
    'Sample Code'=>'样品编号',
    'Close' => '关闭',
    'Please Choose Type'=>'选择类型',
    'Add Samples Max 8 Items'=>'添加样品(最大可添加8个样品)',
    'Basic Information' => '基本信息',
    'Download File' => '下载数据',
    'Next' => '下一步',
    'Proxy Name' => '',
    'Update User' => '编辑用户',
    'Update {modelClass}: ' => '',
    'Han Liang Ce Shi' => '@@含量测试@@',
    'He Ci Ce Shi' => '@@核磁测试@@',
    'Hua Xue Biao Zheng' => '@@化学表征@@',
    'Sample Comment' => '@@样品备注@@',
    'Sample List' => '@@样品列表@@',
    'Sheng Wu Fu Wu' => '@@生物服务@@',
    'create time' => '@@创建时间@@',
    'Address' => '地址',
    'City' => '市',
    'Company Name' => '公司名称',
    'Company Tax' => '公司税号',
    'Complain' => '申诉',
    'Complain List' => '申诉列表',
    'Complain List (history)' => '申诉历史',
    'Complain Reason' => '申诉原因',
    'Create' => '新建',
    'Create Sample' => '添加样品',
    'Create Sample Service' => '添加测试项',
    'Create Test Sheet' => '创建委托检测单',
    'Detail Address' => '详细地址',
    'Different Password' => '密码不同',
    'Email' => '邮件',
    'First Step: Add Basic Information' => '第一步：添加基本信息',
    'Function Doc' => '方法资料',
    'Login' => '登录',
    'Mobile Phone' => '手机号',
    'Navigation' => '导航栏',
    'Next Step' => '下一步',
    'Password' => '密码',
    'Please Choose Service Items(Most Six Items)' => '请选择检测项(最多可选择6项)',
    'Please Choose Unit' => '请选择单位',
    'Please Select ...' => '请选择...',
    'Print' => '打印',
    'Profile' => '简介',
    'Province' => '省',
    'Remember Me' => '记住',
    'Reset' => '重置',
    'Retype password' => '重复密码',
    'Sample' => '样品',
    'Sample Service' => '测试项',
    'Sample Service List' => '服务列表',
    'Sample Services' => '测试项',
    'Samples' => '样品',
    'Search' => '查询',
    'Second Step: Add Samples And Sample Sevices' => '第二步：添加样品和测试项',
    'Select City' => '选择市',
    'Select Custom' => '切换客户',
    'Select Province' => '选择省',
    'Service' => '测试项',
    'Show All Samples' => '显示所有样品',
    'Show All Test Sheets' => '显示所有测试项',
    'Show Samples' => '显示样品',
    'Sign Up' => '注册',
    'Sign out' => '退出',
    'Submit' => '提交',
    'Test Page Order' => '委托检测单',
    'Test Sheet' => '测试单',
    'Test Sheet Comment' => '测试单备注信息',
    'Test Sheet List' => '测试单列表',
    'Test Sheets' => '测试单列表',
    'Update' => '编辑',
    'Update Test Sheet' => '编辑测试单',
    'User Name' => '用户名',
    'Verify Code' => '验证码',
    'Please Choose Type' => '请选择样品形态',
    'sample & serial_number' => '样品名/编号'
];
